import { BsGraphUp } from "react-icons/bs"
import { useEffect, useState } from "react"

function normalizePath(path) {
    if (!path) return null
    return String(path).replace(/\\/g, "/")
}

function toImageUrl(path, apiBaseUrl) {
    const normalizedPath = normalizePath(path)

    if (!normalizedPath) return null

    if (/^https?:\/\//i.test(normalizedPath)) {
        return normalizedPath
    }

    const pathWithLeadingSlash = normalizedPath.startsWith("/")
        ? normalizedPath
        : `/${normalizedPath}`

    return `${apiBaseUrl}${pathWithLeadingSlash}`
}

function getFileName(path) {
    const normalizedPath = normalizePath(path)

    if (!normalizedPath) return ""

    return normalizedPath.split("/").pop()
}

function WorkflowVisualization({ visualization, apiBaseUrl }) {
    const [imageError, setImageError] = useState(false)
    const [activeImageIndex, setActiveImageIndex] = useState(0)

    const imagePaths = visualization?.imagePaths || []
    const activeImagePath = imagePaths[activeImageIndex] || imagePaths[0]

    useEffect(() => {
        setImageError(false)
        setActiveImageIndex(0)
    }, [visualization?.stepId])

    useEffect(() => {
        setImageError(false)
    }, [activeImagePath])

    useEffect(() => {
        if (activeImageIndex >= imagePaths.length) {
            setActiveImageIndex(0)
        }
    }, [activeImageIndex, imagePaths.length])

    if (!visualization) {
        return (
            <div className="w-full flex items-center justify-center flex-col gap-ds-md h-200 shadow-lg bg-light-foam rounded-xl">
                <div className="flex h-14 w-14 items-center justify-center rounded-lg bg-crema/25 shrink-0">
                    <BsGraphUp className="h-7 w-7 text-espresso" />
                </div>
                <span className="w-md text-center text-lg text-espresso/75">
                    Run a visualization method to generate visualization. The result will appear here.
                </span>
            </div>
        )
    }

    const imageUrl = toImageUrl(activeImagePath, apiBaseUrl)

    return (
        <div className="w-full flex flex-col gap-ds-md min-h-200 shadow-lg bg-light-foam rounded-xl px-ds-lg py-ds-md">
            <div className="flex items-center gap-ds-md">
                {/* <div className="flex h-14 w-14 items-center justify-center rounded-lg bg-crema/25 shrink-0">
                    <BsGraphUp className="h-7 w-7 text-espresso" />
                </div> */}
                <div>
                    <h2 className="text-xl font-semibold text-espresso">
                        {visualization.title}
                    </h2>
                    <p className="text-base text-espresso/75">
                        Generated by step number {visualization.stepNumber}
                    </p>
                </div>
            </div>

            {imagePaths.length > 1 && (
                <div className="flex gap-ds-sm flex-wrap">
                    {imagePaths.map((path, index) => (
                        <button
                            key={path}
                            type="button"
                            onClick={() => setActiveImageIndex(index)}
                            className={`px-ds-md py-ds-sm rounded-md text-sm cursor-pointer
                                ${activeImageIndex === index ? "text-foam bg-espresso font-semibold" : "text-espresso border-2 border-roast/25"}`}
                            title={getFileName(path)}
                        >
                            Image {index + 1}
                        </button>
                    ))}
                </div>
            )}

            {imageError ? (
                <div className="flex items-center justify-center h-120 rounded-lg bg-white border border-roast/20">
                    <p className="text-espresso/75 text-center">
                        The image was generated, but it could not be loaded in the frontend.
                        Check whether the backend is running and whether the image path exists.
                    </p>
                </div>
            ) : (
                <img
                    src={imageUrl}
                    alt={visualization.title}
                    className="w-full max-h-176 object-contain rounded-lg bg-white border border-roast/25 p-ds-sm"
                    onError={() => setImageError(true)}
                    onLoad={() => setImageError(false)}
                />
            )}

            <div className="flex justify-between items-center">
                {/* <span>{normalizePath(activeImagePath)}</span> */}
                <span></span>
                <a
                    href={imageUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="text-espresso underline text-medium text-base"
                >
                    Open image
                </a>
            </div>
        </div >
    )
}

export default WorkflowVisualization